version: "3"
services:
    app.3080:
        image: mzzhmh/httpsproxy:latest
        network_mode: host
        volumes:
          - /var/log/powerwall/:/var/log/powerwall/
        working_dir: /opt/httpsProxy/
        container_name: pythonservercontaine3080
        command: ["/usr/bin/bash", "-c", "/opt/httpsProxy/app.py 127.0.0.1 3080 &>/var/log/powerwall/3080_log"]
        restart: always
    app.3032:
        image: mzzhmh/httpsproxy:latest
        network_mode: host
        volumes:
          - /var/log/powerwall/:/var/log/powerwall/
        working_dir: /opt/httpsProxy/
        container_name: pythonservercontainer3032
        command: ["/usr/bin/bash", "-c", "/opt/httpsProxy/app.py 127.0.0.1 3032 &>/var/log/powerwall/3032_log"]
        restart: always
    app.4444:
        image: mzzhmh/httpsproxy:latest
        network_mode: host
        volumes:
          - /var/log/powerwall/:/var/log/powerwall/
        working_dir: /opt/httpsProxy/
        container_name: pythonservercontainer4444
        command: ["/usr/bin/bash", "-c", "/opt/httpsProxy/app.py 127.0.0.1 4444 &>/var/log/powerwall/4444_log"]
        restart: always

