version: "3"
services:
    app.3080:
        image: pythonserverrun:latest
        network_mode: host
        volumes:
          - /var/log/powerwall/:/var/log/powerwall/
        working_dir: /opt/restfulPowerwall/
        container_name: pythonservercontaine3080
        command: ["/usr/bin/bash", "-c", "/opt/restfulPowerwall/app.py ${SITE1} ${SITE1_PORT} &>/var/log/powerwall/3080_log"]
        restart: always
    app.3032:
        image: pythonserverrun:latest
        network_mode: host
        volumes:
          - /var/log/powerwall/:/var/log/powerwall/
        working_dir: /opt/restfulPowerwall/
        container_name: pythonservercontainer3032
        command: ["/usr/bin/bash", "-c", "/opt/restfulPowerwall/app.py ${SITE2} ${SITE2_PORT} &>/var/log/powerwall/3032_log"]
        restart: always
    app.4444:
        image: pythonserverrun:latest
        network_mode: host
        volumes:
          - /var/log/powerwall/:/var/log/powerwall/
        working_dir: /opt/restfulPowerwall/
        container_name: pythonservercontainer4444
        command: ["/usr/bin/bash", "-c", "/opt/restfulPowerwall/app.py ${SITE3} ${SITE3_PORT} &>/var/log/powerwall/4444_log"]
        restart: always

